[windows]
installs = "winget install Neovim.Neovim"
[windows.links]
"init.lua" = "~\\AppData\\Local\\nvim\\init.lua"
"ginit.vim" = "~\\AppData\\Local\\nvim\\ginit.vim"
lua = "~\\AppData\\Local\\nvim\\lua"
after = "~\\AppData\\Local\\nvim\\after"
queries = "~\\AppData\\Local\\nvim\\queries"

["linux|darwin"]
installs = "brew install neovim"

["linux|darwin".links]
"init.lua" = "~/.config/nvim/init.lua"
"ginit.vim" = "~/.config/nvim/ginit.vim"
lua = "~/.config/nvim/lua"
after = "~/.config/nvim/after"
queries = "~/.config/nvim/queries"
